### ISSUE TITLE
unsafe_textures

### ISSUE THREAD

**Issue by WiktorJanecki** [neonmoe/fontdue-sdl2#3]
A lot of people use sdl2 with unsafe_textures feature. Unfortunately, it does not compile with the current version of this crate. I implemented it but I don't know if you will like the implementation. #2

**Comment by neonmoe** [comment]
I'll have a closer look at this further when I have the time (and perhaps when I continue work on this crate), but thanks for the contribution! Hopefully it helps others in the same boat in the meanwhile.

**Comment by neonmoe** [comment]
This was actually merged and published in 0.3, closing now. Thanks again for the PR!
